export const Newses = [
    {
        key: 1,
        type: 'blog',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 2,
        type: 'blog',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 3,
        type: 'blog',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 4,
        type: 'blog',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 5,
        type: 'blog',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 6,
        type: 'blog',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 7,
        type: 'blog',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 8,
        type: 'blog',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 9,
        type: 'blog',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },

    {
        key: 10,
        type: 'computer',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 11,
        type: 'computer',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 12,
        type: 'computer',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 13,
        type: 'computer',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 14,
        type: 'computer',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 15,
        type: 'computer',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 16,
        type: 'computer',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 17,
        type: 'computer',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 18,
        type: 'computer',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 19,
        type: 'computer',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 20,
        type: 'computer',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 21,
        type: 'computer',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },

    {
        key: 22,
        type: 'coronavirus',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 23,
        type: 'coronavirus',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 24,
        type: 'coronavirus',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 25,
        type: 'coronavirus',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },


    {
        key: 26,
        type: 'postformat',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 27,
        type: 'postformat',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 28,
        type: 'postformat',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 29,
        type: 'postformat',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 30,
        type: 'postformat',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 31,
        type: 'postformat',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 32,
        type: 'postformat',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },

    {
        key: 33,
        type: 'provideassistance',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },


    {
        key: 34,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 35,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 36,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 37,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 38,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 39,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 40,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 41,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 42,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 43,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 44,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 45,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 46,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 47,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 48,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 49,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 50,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 51,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 52,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 53,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 54,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 55,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 56,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 57,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 58,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 59,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 60,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 61,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 62,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 63,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 64,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 65,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 66,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 67,
        type: 'uncategorized',
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Equipping Researchers in the Developing World',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 68,
        type: 'uncategorized',
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Patient experience better Health Your Doctor Wishes',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        key: 69,
        type: 'uncategorized',
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        email: 'heartberryoverseas@gmail.com',
        comments: 'No Comments',
        title: 'Standards of treatment Improved Detection of Disease',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
]

export const blogdetails = [
    {
        key: 1,
        img: 'assets/images/blog/01.jpeg',
        date: '20 April',
        title: 'Equipping Researchers in the Developing World',
    }
]

export const blogdetaillatest = [
    {
        key: 1,
        img: 'assets/images/blog/02.jpeg',
        date: '15 August',
        title: 'Patient experience better Health Your Doctor Wishes',
    },
    {
        key: 2,
        img: 'assets/images/blog/03.jpeg',
        date: '13 September',
        title: 'Standards of treatment Improved Detection of Disease',
    },
]