// ---------- Product Page Data Start ---------- //
export const Sortby = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
    {
        key: 14,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
    },
    {
        key: 15,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$138.00',
        new_price: '$89.00',
    },
    {
        key: 16,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$121.00',
        new_price: '$115.00',
    },
    {
        key: 17,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$162.00',
        new_price: '$150.00',
    },
    {
        key: 18,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$88.00',
        new_price: '$80.00',
    },
]

export const Popularity = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
]

export const Average_Rating = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
    {
        key: 14,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
    },
]

export const Latest = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
]

export const Cancer_Medicines = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
    {
        key: 14,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
    },
    {
        key: 15,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$138.00',
        new_price: '$89.00',
    },
    {
        key: 16,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$121.00',
        new_price: '$115.00',
    },
]

export const Hepatitis_A = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
]

export const Hepatitis_B = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
]

export const Hepatitis_C = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
]

export const Hepatitis_Medicines = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
]

export const Hiv = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
]

export const Rheumatology = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
    },
]

export const Uncategorized = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/shopdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
    },
]

// ---------- Product Page Data End ---------- //