// ---------- Product Page Data Start ---------- //
export const Sortby = [
    {
        key: 1,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'sortby',
    },
    {
        key: 2,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'sortby',
    },
    {
        key: 3,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'sortby',
    },
    {
        key: 4,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'sortby',
    },
    {
        key: 5,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'sortby',
    },
    {
        key: 6,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'sortby',
    },
    {
        key: 7,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'sortby',
    },
    {
        key: 8,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'sortby',
    },
    {
        key: 9,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'sortby',
    },
    {
        key: 10,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'sortby',
    },
    {
        key: 11,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type: 'sortby',
    },
    {
        key: 12,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type: 'sortby',
    },
    {
        key: 13,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type: 'sortby',
    },
    {
        key: 14,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
        type: 'sortby',
    },
    {
        key: 15,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$138.00',
        new_price: '$89.00',
        type: 'sortby',
    },
    {
        key: 16,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$121.00',
        new_price: '$115.00',
        type: 'sortby',
    },
    {
        key: 17,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$162.00',
        new_price: '$150.00',
        type: 'sortby',
    },
    {
        key: 18,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$88.00',
        new_price: '$80.00',
        type: 'sortby',
    },
    {
        key: 19,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'popolarity',
    },
    {
        key: 20,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'popolarity',
    },
    {
        key: 21,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'popolarity',
    },
    {
        key: 22,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'popolarity',
    },
    {
        key: 23,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'popolarity',
    },
    {
        key: 24,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'popolarity',
    },
    {
        key: 25,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'popolarity',
    },
    {
        key: 26,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'popolarity',
    },
    {
        key: 27,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'popolarity',
    },
    {
        key: 28,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'popolarity',
    },
    {
        key: 29,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'averageratting',
    },
    {
        key: 30,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'averageratting',
    },
    {
        key: 31,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'averageratting',
    },
    {
        key: 32,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'averageratting',
    },
    {
        key: 33,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'averageratting',
    },
    {
        key: 34,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'averageratting',
    },
    {
        key: 35,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'averageratting',
    },
    {
        key: 36,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'averageratting',
    },
    {
        key: 37,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'averageratting',
    },
    {
        key: 38,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'averageratting',
    },
    {
        key: 39,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type: 'averageratting',
    },
    {
        key: 40,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type: 'averageratting',
    },
    {
        key: 41,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type: 'averageratting',
    },
    {
        key: 42,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
        type: 'averageratting',
    },
    {
        key: 43,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'latest',
    },
    {
        key: 44,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'latest',
    },
    {
        key: 45,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'latest',
    },
    {
        key: 46,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'latest',
    },
    {
        key: 47,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'latest',
    },
    {
        key: 48,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'cancermedicines',
    },
    {
        key: 49,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'cancermedicines',
    },
    {
        key: 50,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'cancermedicines',
    },
    {
        key: 51,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'cancermedicines',
    },
    {
        key: 52,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'cancermedicines',
    },
    {
        key: 56,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'cancermedicines',
    },
    {
        key: 57,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'cancermedicines',
    },
    {
        key: 58,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'cancermedicines',
    },
    {
        key: 59,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'cancermedicines',
    },
    {
        key: 60,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'cancermedicines',
    },
    {
        key: 61,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type: 'cancermedicines',
    },
    {
        key: 62,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type: 'cancermedicines',
    },
    {
        key: 63,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type: 'cancermedicines',
    },
    {
        key: 64,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$140.00',
        new_price: '$120.00',
        type: 'cancermedicines',
    },
    {
        key: 65,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$138.00',
        new_price: '$89.00',
        type: 'cancermedicines',
    },
    {
        key: 66,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$121.00',
        new_price: '$115.00',
        type: 'cancermedicines',
    },
    {
        key: 67,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'hepatitisA',
    },
    {
        key: 68,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'hepatitisA',
    },
    {
        key: 69,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'hepatitisA',
    },
    {
        key: 70,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'hepatitisB',
    },
    {
        key: 71,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'hepatitisB',
    },
    {
        key: 72,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'hepatitisB',
    },
    {
        key: 73,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'hepatitisB',
    },
    {
        key: 74,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'hepatitisB',
    },
    {
        key: 75,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'hepatitisB',
    },
    {
        key: 76,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'hepatitisB',
    },
    {
        key: 77,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'hepatitisB',
    },
    {
        key: 78,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'hepatitisB',
    },
    {
        key: 79,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'hepatitisB',
    },
    {
        key: 80,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type: 'hepatitisB',
    },
    {
        key: 81,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type: 'hepatitisB',
    },
    {
        key: 82,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type: 'hepatitisB',
    },
    {
        key: 83,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'hepatitisC',
    },
    {
        key: 84,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'hepatitisC',
    },
    {
        key: 85,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'hepatitisC',
    },
    {
        key: 86,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'hepatitisC',
    },
    {
        key: 87,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'hepatitisC',
    },
    {
        key: 88,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'hepatitisC',
    },
    {
        key: 89,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type: 'hepatitismedicines',
    },
    {
        key: 90,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type: 'hepatitismedicines',
    },
    {
        key: 100,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type: 'hepatitismedicines',
    },
    {
        key: 101,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type: 'hepatitismedicines',
    },
    {
        key: 102,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type: 'hepatitismedicines',
    },
    {
        key: 103,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type: 'hepatitismedicines',
    },
    {
        key: 104,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type: 'hepatitismedicines',
    },
    {
        key: 105,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type: 'hepatitismedicines',
    },
    {
        key: 106,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type: 'hepatitismedicines',
    },
    {
        key: 107,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type: 'hepatitismedicines',
    },
    {
        key: 108,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type: 'hepatitismedicines',
    },
    {
        key: 109,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type: 'hepatitismedicines',
    },
    {
        key: 110,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type: 'hepatitismedicines',
    },
    {
        key: 111,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type:'hiv',
    },
    {
        key: 112,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type:'hiv',
    },
    {
        key: 113,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type:'hiv',
    },
    {
        key: 114,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type:'hiv',
    },
    {
        key: 115,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type:'hiv',
    },
    {
        key: 116,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type:'hiv',
    },
    {
        key: 117,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type:'hiv',
    },
    {
        key: 118,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type:'hiv',
    },
    {
        key: 119,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type:'hiv',
    },
    {
        key: 120,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type:'hiv',
    },
    {
        key: 121,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type:'rheumatology',
    },
    {
        key: 122,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$75.00',
        new_price: '$60.00',
        type:'rheumatology',
    },
    {
        key: 123,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$83.00',
        new_price: '$55.00',
        type:'rheumatology',
    },
    {
        key: 124,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$58.00',
        type:'rheumatology',
    },
    {
        key: 125,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$90.00',
        new_price: '$85.00',
        type:'rheumatology',
    },
    {
        key: 126,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$65.00',
        new_price: '$40.00',
        type:'rheumatology',
    },
    {
        key: 127,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$89.00',
        new_price: '$20.00',
        type:'rheumatology',
    },
    {
        key: 128,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$105.00',
        new_price: '$93.00',
        type:'rheumatology',
    },
    {
        key: 129,
        image: 'assets/images/product/04.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$200.00',
        new_price: '$185.00',
        type:'rheumatology',
    },
    {
        key: 130,
        image: 'assets/images/product/05.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$299.00',
        new_price: '$208.00',
        type:'rheumatology',
    },
    {
        key: 131,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$98.00',
        new_price: '$86.00',
        type:'rheumatology',
    },
    {
        key: 132,
        image: 'assets/images/product/02.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$184.00',
        new_price: '$152.00',
        type:'rheumatology',
    },
    {
        key: 133,
        image: 'assets/images/product/03.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$212.00',
        new_price: '$195.00',
        type:'rheumatology',
    },
    {
        key: 134,
        image: 'assets/images/product/01.jpeg',
        card_link: '/medicinesdetails',
        cart_link: '/productcart',
        wishlist_link: '/productcheckout',
        name: 'Dealistic Microscope',
        old_price: '$15.00',
        new_price: '$10.00',
        type:'uncategorized',
    },
]

// ---------- Product Page Data End ---------- //